#ifndef DASHBOARD_H
#define DASHBOARD_H

#include <stddef.h>

static const char dashboard_html[] =
"<!DOCTYPE html>"
"<html><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Thermal Management</title>"
""
"<style>"
"*{box-sizing:border-box;margin:0;padding:0;font-family:system-ui,sans-serif}"
"body{padding:16px;background:#1a1a2e;color:#eee}"
".header{display:flex;gap:16px;flex-wrap:wrap;align-items:center;margin-bottom:16px}"
".card{background:#16213e;border-radius:12px;padding:16px;margin-bottom:12px}"
".value{font-size:2em;font-weight:700}"
".label{font-size:.8em;color:#888;text-transform:uppercase}"
".charts{display:grid;grid-template-columns:1fr 1fr;gap:12px}"
".controls{display:flex;gap:12px;flex-wrap:wrap;align-items:center}"
"button{padding:8px 20px;border:none;border-radius:8px;cursor:pointer;font-size:1em}"
".active{background:#0f3460;color:#fff}"
".inactive{background:#333;color:#aaa}"
"input[type=range]{flex:1;min-width:120px;accent-color:#4fc3f7}"
"table{width:100%;border-collapse:collapse;font-size:.85em}"
"th,td{padding:6px 8px;text-align:left;border-bottom:1px solid #333}"
"th{color:#888}"
".badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:.8em}"
".badge.auto{background:#0f3460;color:#4fc3f7}"
".badge.manual{background:#4a148c;color:#ce93d8}"
".badge.offline{background:#b71c1c;color:#ffcdd2}"
"@media(max-width:600px){.charts{grid-template-columns:1fr}}"
".log-wrap{max-height:300px;overflow-y:auto}"
".actions{display:flex;gap:8px;margin-top:8px;flex-wrap:wrap}"
".actions a{color:#4fc3f7;text-decoration:none;padding:6px 12px;border:1px solid #4fc3f7;border-radius:6px;font-size:.85em}"
".actions a.danger{color:#ef5350;border-color:#ef5350}"
".wifi-badge{font-size:.7em;color:#666;margin-left:8px}"
"</style></head><body>"

"<div class='header'>"
"<div class='card'><div class='label'>Temperature</div><div class='value' id='temp'>--</div></div>"
"<div class='card'><div class='label'>Fan Speed</div><div class='value' id='fan'>--</div></div>"
"<div class='card'><div class='label'>Mode</div><div id='mode'><span class='badge auto'>AUTO</span></div></div>"
"<div class='card'><div class='label'>Setpoint</div><div class='value' id='setpoint'>--</div></div>"
"</div>"

"<div class='charts'>"
"<div class='card'><canvas id='tempChart'></canvas></div>"
"<div class='card'><canvas id='fanChart'></canvas></div>"
"</div>"

"<div class='card'>"
"<div class='controls'>"
"<button id='btnMode' onclick='toggleMode()' class='active'>Toggle Mode</button>"
"<span class='label'>Setpoint:</span>"
"<input type='range' id='slSetpoint' min='20' max='60' step='0.5' oninput='sendControl()'>"
"<span id='spVal'>30.0</span>"
"<span class='label' style='margin-left:12px'>Fan:</span>"
"<input type='range' id='slFan' min='0' max='100' oninput='sendControl()'>"
"<span id='fanVal'>0%</span>"
"<span id='wifiBadge' class='wifi-badge'></span>"
"</div>"
"</div>"

"<div class='card'>"
"<div class='log-wrap'><table><thead><tr>"
"<th>#</th><th>Time(ms)</th><th>Temp</th><th>Fan</th><th>Mode</th><th>Setpoint</th>"
"</tr></thead><tbody id='logBody'></tbody></table></div>"
"<div class='actions'>"
"<a href='/api/log/csv' download>Download CSV</a>"
"<a href='/api/log/plt' download>Download .plt</a>"
"<a href='#' onclick='clearLog()' class='danger'>Clear Log</a>"
"</div>"
"</div>"

"<script>"
"const PAD={top:12,bot:28,lft:40,rgt:12};"
"function drawGraph(canvas,data,minY,maxY,color,label){"
"  const rect=canvas.parentElement.getBoundingClientRect();"
"  canvas.width=rect.width-32;canvas.height=180;"
"  const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;"
"  const pw=w-PAD.lft-PAD.rgt,ph=h-PAD.top-PAD.bot;"
"  ctx.clearRect(0,0,w,h);"
"  ctx.strokeStyle='#333';ctx.lineWidth=1;"
"  for(let i=0;i<=4;i++){"
"    const y=PAD.top+(ph/4)*i;"
"    ctx.beginPath();ctx.moveTo(PAD.lft,y);ctx.lineTo(w-PAD.rgt,y);ctx.stroke();"
"    const val=maxY-((maxY-minY)/4)*i;"
"    ctx.fillStyle='#666';ctx.font='10px monospace';ctx.textAlign='right';"
"    ctx.fillText(val.toFixed(1),PAD.lft-4,y+3);"
"  }"
"  ctx.fillStyle='#555';ctx.font='10px monospace';ctx.textAlign='center';"
"  ctx.fillText(label,w/2,h-4);"
"  if(!data||data.length<2)return;"
"  const step=pw/(data.length-1);"
"  const rng=maxY-minY||1;"
"  ctx.beginPath();"
"  for(let i=0;i<data.length;i++){"
"    const x=PAD.lft+i*step;"
"    const y=PAD.top+ph-(data[i]-minY)/rng*ph;"
"    i===0?ctx.moveTo(x,y):ctx.lineTo(x,y);"
"  }"
"  ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();"
"}"
"let tempData=[],fanData=[];"
"let mode=0;"
"async function poll(){"
"  try{"
"    const r=await fetch('/api/status');"
"    if(!r.ok)throw new Error('HTTP '+r.status);"
"    const d=await r.json();"
"    document.getElementById('temp').textContent=d.temp.toFixed(1)+'°C';"
"    let fanPct=d.fan;"
"    document.getElementById('fan').textContent=fanPct+'%';"
"    const md=document.getElementById('mode');"
"    if(d.mode===0)md.innerHTML='<span class=\"badge auto\">AUTO</span>';"
"    else md.innerHTML='<span class=\"badge manual\">MANUAL</span>';"
"    document.getElementById('setpoint').textContent=d.setpoint.toFixed(1)+'°C';"
"    mode=d.mode;"
"    tempData.push(d.temp);if(tempData.length>60)tempData.shift();"
"    fanData.push(fanPct);if(fanData.length>60)fanData.shift();"
"    drawGraph(document.getElementById('tempChart'),tempData,0,60,'#4fc3f7','Temperature (°C)');"
"    drawGraph(document.getElementById('fanChart'),fanData,0,100,'#ce93d8','Fan Speed (%)');"
"    document.getElementById('wifiBadge').textContent=d.wifi;"
"  }catch(e){"
"    document.getElementById('temp').textContent='Err';"
"    document.getElementById('wifiBadge').textContent='Error: '+e.message;"
"  }"
"  setTimeout(poll,500);"
"}"
"poll();"
"async function toggleMode(){"
"  const nm=mode===0?1:0;"
"  await fetch('/api/control',{method:'POST',body:JSON.stringify({mode:nm})});"
"}"
"async function sendControl(){"
"  const sp=parseFloat(document.getElementById('slSetpoint').value);"
"  const fnPct=parseInt(document.getElementById('slFan').value);"
"  const fnRaw=Math.round((fnPct/100)*255);"
"  document.getElementById('spVal').textContent=sp.toFixed(1);"
"  document.getElementById('fanVal').textContent=fnPct+'%';"
"  await fetch('/api/control',{method:'POST',body:JSON.stringify({setpoint:sp,fan:fnRaw})});"
"}"
"async function clearLog(){await fetch('/api/log/clear',{method:'POST'});}"
"setTimeout(function(){"
"  document.getElementById('tempChart').parentElement.style.minHeight='200px';"
"  document.getElementById('fanChart').parentElement.style.minHeight='200px';"
"},100);"
"</script></body></html>";

static const size_t dashboard_html_len = sizeof(dashboard_html) - 1;

#endif