#ifndef DASHBOARD_H
#define DASHBOARD_H

#include <stddef.h>

static const char dashboard_html[] =
"<!DOCTYPE html>"
"<html><head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Thermal Management</title>"
"<script src='https://cdn.jsdelivr.net/npm/chart.js'></script>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0;font-family:system-ui,sans-serif}"
"body{padding:16px;background:#1a1a2e;color:#eee}"
".header{display:flex;gap:16px;flex-wrap:wrap;align-items:center;margin-bottom:16px}"
".card{background:#16213e;border-radius:12px;padding:16px;margin-bottom:12px}"
".value{font-size:2em;font-weight:700}"
".label{font-size:.8em;color:#888;text-transform:uppercase}"
".charts{display:grid;grid-template-columns:1fr 1fr;gap:12px}"
".controls{display:flex;gap:12px;flex-wrap:wrap;align-items:center}"
"button{padding:8px 20px;border:none;border-radius:8px;cursor:pointer;font-size:1em}"
".active{background:#0f3460;color:#fff}"
".inactive{background:#333;color:#aaa}"
"input[type=range]{flex:1;min-width:120px;accent-color:#4fc3f7}"
"table{width:100%;border-collapse:collapse;font-size:.85em}"
"th,td{padding:6px 8px;text-align:left;border-bottom:1px solid #333}"
"th{color:#888}"
".badge{display:inline-block;padding:2px 8px;border-radius:4px;font-size:.8em}"
".badge.auto{background:#0f3460;color:#4fc3f7}"
".badge.manual{background:#4a148c;color:#ce93d8}"
".badge.offline{background:#b71c1c;color:#ffcdd2}"
"@media(max-width:600px){.charts{grid-template-columns:1fr}}"
".log-wrap{max-height:300px;overflow-y:auto}"
".actions{display:flex;gap:8px;margin-top:8px;flex-wrap:wrap}"
".actions a{color:#4fc3f7;text-decoration:none;padding:6px 12px;border:1px solid #4fc3f7;border-radius:6px;font-size:.85em}"
".actions a.danger{color:#ef5350;border-color:#ef5350}"
".wifi-badge{font-size:.7em;color:#666;margin-left:8px}"
"</style></head><body>"

"<div class='header'>"
"<div class='card'><div class='label'>Temperature</div><div class='value' id='temp'>--</div></div>"
"<div class='card'><div class='label'>Fan Speed</div><div class='value' id='fan'>--</div></div>"
"<div class='card'><div class='label'>Mode</div><div id='mode'><span class='badge auto'>AUTO</span></div></div>"
"<div class='card'><div class='label'>Setpoint</div><div class='value' id='setpoint'>--</div></div>"
"</div>"

"<div class='charts'>"
"<div class='card'><canvas id='tempChart'></canvas></div>"
"<div class='card'><canvas id='fanChart'></canvas></div>"
"</div>"

"<div class='card'>"
"<div class='controls'>"
"<button id='btnMode' onclick='toggleMode()' class='active'>Toggle Mode</button>"
"<span class='label'>Setpoint:</span>"
"<input type='range' id='slSetpoint' min='20' max='60' step='0.5' oninput='sendControl()'>"
"<span id='spVal'>30.0</span>"
"<span class='label' style='margin-left:12px'>Fan:</span>"
"<input type='range' id='slFan' min='0' max='100' oninput='sendControl()'>"
"<span id='fanVal'>0%</span>"
"<span id='wifiBadge' class='wifi-badge'></span>"
"</div>"
"</div>"

"<div class='card'>"
"<div class='log-wrap'><table><thead><tr>"
"<th>#</th><th>Time(ms)</th><th>Temp</th><th>Fan</th><th>Mode</th><th>Setpoint</th>"
"</tr></thead><tbody id='logBody'></tbody></table></div>"
"<div class='actions'>"
"<a href='/api/log/csv' download>Download CSV</a>"
"<a href='/api/log/plt' download>Download .plt</a>"
"<a href='#' onclick='clearLog()' class='danger'>Clear Log</a>"
"</div>"
"</div>"

"<script>"
"const tc=document.getElementById('tempChart').getContext('2d');"
"const fc=document.getElementById('fanChart').getContext('2d');"
"const tempCh=new Chart(tc,{type:'line',data:{labels:[],datasets:[{label:'Temperature (°C)',data:[],borderColor:'#4fc3f7',fill:false,tension:.3}]},options:{responsive:true,animation:false,scales:{x:{display:false},y:{min:0,max:60}}}});"
"const fanCh=new Chart(fc,{type:'line',data:{labels:[],datasets:[{label:'Fan PWM (%)',data:[],borderColor:'#ce93d8',fill:false,tension:.3}]},options:{responsive:true,animation:false,scales:{x:{display:false},y:{min:0,max:100}}}});"
"let mode=0;"
"async function poll(){"
"try{"
"const r=await fetch('/api/status');const d=await r.json();"
"document.getElementById('temp').textContent=d.temp.toFixed(1)+'°C';"
"const fanEl=document.getElementById('fan');fanEl.textContent=d.fan+'%';"
"const md=document.getElementById('mode');"
"if(d.mode===0)md.innerHTML='<span class=\"badge auto\">AUTO</span>';"
"else md.innerHTML='<span class=\"badge manual\">MANUAL</span>';"
"document.getElementById('setpoint').textContent=d.setpoint.toFixed(1)+'°C';"
"mode=d.mode;"
"tempCh.data.labels.push('');tempCh.data.datasets[0].data.push(d.temp);"
"if(tempCh.data.labels.length>60){tempCh.data.labels.shift();tempCh.data.datasets[0].data.shift()}"
"fanCh.data.labels.push('');fanCh.data.datasets[0].data.push(d.fan);"
"if(fanCh.data.labels.length>60){fanCh.data.labels.shift();fanCh.data.datasets[0].data.shift()}"
"tempCh.update();fanCh.update();"
"document.getElementById('wifiBadge').textContent=d.wifi;"
"}catch(e){}"
"setTimeout(poll,500);"
"}"
"poll();"
"async function toggleMode(){"
"const nm=mode===0?1:0;"
"await fetch('/api/control',{method:'POST',body:JSON.stringify({mode:nm})});"
"}"
"async function sendControl(){"
"const sp=parseFloat(document.getElementById('slSetpoint').value);"
"const fn=parseInt(document.getElementById('slFan').value);"
"document.getElementById('spVal').textContent=sp.toFixed(1);"
"document.getElementById('fanVal').textContent=fn+'%';"
"await fetch('/api/control',{method:'POST',body:JSON.stringify({setpoint:sp,fan:fn})});"
"}"
"async function clearLog(){await fetch('/api/log/clear',{method:'POST'});}"
"</script></body></html>";

static const size_t dashboard_html_len = sizeof(dashboard_html) - 1;

#endif